'use client';
import { useEffect, useRef, useState } from 'react';
import { Slider } from '@/components/ui/slider';
import { Play, Pause, SkipBack, ZoomIn, ZoomOut, ScanLine, MousePointer2, ChevronRight, AudioLines, SlidersHorizontal, Flag, X, Crosshair, Brackets, Clock3 } from 'lucide-react';
const END=22800;
const fmt=(n:number)=>(n/1000).toFixed(3)+' s';
type Clip={a:number;b:number;label:string;sub?:string;event?:number;wave?:boolean;muted?:boolean};
const events=[
 {id:0,t:3600,end:4000,name:'打断 01',title:'等待中补充',quote:'“主要……看下午，我要出去跑步。”',tag:'音频打断',plan:'嗯……好的，你稍等一下，我来看看。',heard:'嗯……好的，你稍等一下……',drop:'我来看看',actions:['检测到用户介入，让出话权','audio.stop() 停止当前播报','weather.query 继续执行','接收下午、跑步的关注条件'],tool:'查询继续 · 无需重查',note:'现有查询包含逐小时天气。用户打断音频，不取消后台请求。',overlap:[3600,3760]},
 {id:1,t:12000,end:12400,name:'打断 02',title:'播报中切换时段',quote:'“那上午呢？”',tag:'音频打断',plan:'明天下午三点左右有小雨，气温二十度，跑步可以……',heard:'明天下午三点左右有小雨……',drop:'气温二十度，跑步可以……',actions:['识别上午时段，停止下午播报','audio.stop() 停止当前播报','读取已经返回的上午天气','结合跑步用途重新组织回复'],tool:'读取已有数据 · 不调用 API',note:'12,800–15,600 播出：上午多云，十七到十九度，比下午更适合跑步。',overlap:[12000,12160]},
 {id:2,t:18400,end:19600,name:'改口 03',title:'工具执行中改时间',quote:'“不，改成九点。”',tag:'意图修正',plan:'创建明天 08:00 的跑步提醒；结果需与最新意图核对。',heard:'行。',drop:'08:00 提醒已创建的过时反馈',actions:['更新最新目标：09:00','等待 R1 返回 08:00 提醒','reminder.update(id, 09:00)','修改成功后才播报完成'],tool:'R1 → update → success',note:'这是用户语音与工具执行的重叠。没有 Assistant 播报，不属于双音频重叠。',overlap:null},
];
const tracks:{name:string;en:string;color:string;clips:Clip[]}[]=[
 {name:'用户音频',en:'USER · AUDIO',color:'green',clips:[{a:0,b:2400,label:'帮我看看明天北京的天气。',wave:true},{a:3600,b:5600,label:'主要看下午，我要出去跑步。',wave:true,event:0},{a:12000,b:12400,label:'那上午呢？',wave:true,event:1},{a:15600,b:18000,label:'明天早上八点提醒我跑步。',wave:true},{a:18400,b:19600,label:'不，改成九点。',wave:true,event:2}]},
 {name:'Assistant 实播',en:'ASSISTANT · AUDIO',color:'blue',clips:[{a:2400,b:3760,label:'嗯……好的，你稍等一下……',wave:true,event:0,sub:'0.85× 语速 · 尾部示意'},{a:5600,b:6800,label:'行，我看看下午适不适合跑步。',wave:true},{a:10800,b:12160,label:'明天下午三点左右有小雨……',wave:true,event:1},{a:12800,b:15600,label:'上午多云，十七到十九度，比下午更适合跑步。',wave:true},{a:18000,b:18400,label:'行。',wave:true},{a:20400,b:22800,label:'设好了，明天早上九点提醒你跑步。',wave:true}]},
 {name:'后台判断',en:'REASONING · INTENT',color:'amber',clips:[{a:0,b:2400,label:'提取：北京 / 明天'},{a:3600,b:5600,label:'检测介入 → 让出话权',event:0},{a:5600,b:10400,label:'关注下午 + 跑步 · 持续收听'},{a:10400,b:10800,label:'提取下午天气'},{a:12000,b:12800,label:'切换上午 · 保留跑步用途',event:1},{a:15600,b:18000,label:'新任务：明天 08:00 跑步'},{a:18400,b:20400,label:'最新目标 → 09:00',event:2}]},
 {name:'音频控制',en:'CONTROL · EVENTS',color:'pink',clips:[{a:3600,b:4000,label:'audio.stop()',sub:'检出 / 指令 / 停声待实测',event:0},{a:12000,b:12400,label:'audio.stop()',sub:'丢弃剩余下午播报',event:1}]},
 {name:'工具执行',en:'TOOLS · ASYNC',color:'teal',clips:[{a:2400,b:10400,label:'weather.query(北京, 明天)',sub:'8,000 ms · 停播不取消查询',event:0},{a:12000,b:12800,label:'读取已有上午数据',event:1},{a:18000,b:19600,label:'R1 · create(08:00)',sub:'执行中收到改口',event:2},{a:19600,b:20400,label:'update(09:00)',sub:'成功后反馈',event:2}]},
 {name:'回复计划',en:'RESPONSE · CONTROL',color:'purple',clips:[{a:2400,b:3600,label:'嗯……好的，你稍等一下，我来看看。',event:0},{a:3600,b:4000,label:'丢弃：我来看看',muted:true,event:0},{a:6800,b:10400,label:'安静等待 · 不填充话术'},{a:10400,b:12000,label:'下午小雨、二十度、跑步建议',event:1},{a:12000,b:12400,label:'丢弃：下午建议',muted:true,event:1},{a:12400,b:15600,label:'重新组织上午的跑步建议'},{a:18400,b:20400,label:'抑制过时的 08:00 结果',muted:true,event:2},{a:20400,b:22800,label:'确认明天 09:00 提醒'}]},
];
function Wave({width,seed}:{width:number;seed:number}){const n=Math.max(3,Math.floor(width/5));return <svg className="wave" width={width} height="32" aria-hidden="true">{Array.from({length:n},(_,i)=>{const h=3+Math.abs(Math.sin(i*1.8+seed)*Math.cos(i*.23+seed))*26;return <line key={i} x1={i*5+2} x2={i*5+2} y1={(32-h)/2} y2={(32+h)/2}/>})}</svg>}
export default function Studio(){
 const [scale,setScale]=useState(210),[pos,setPos]=useState(3600),[playing,setPlaying]=useState(false),[selected,setSelected]=useState<number|null>(0),[range,setRange]=useState<[number,number]>([3600,4000]),[snap,setSnap]=useState(false),[custom,setCustom]=useState(''),[saved,setSaved]=useState<Record<number,string>>({});
 const scroller=useRef<HTMLDivElement>(null),drag=useRef<{x:number;t:number}|null>(null),moved=useRef(false),jump=useRef<number|null>(2400);
 const width=END/1000*scale,e=selected===null?null:events[selected];
 const px=(t:number)=>t/1000*scale;
 useEffect(()=>{if(jump.current!==null&&scroller.current){scroller.current.scrollLeft=jump.current/1000*scale;jump.current=null}},[scale]);
 useEffect(()=>{if(!playing)return;let prev=performance.now();const id=setInterval(()=>{const now=performance.now(),dt=now-prev;prev=now;setPos(p=>{if(p+dt>=END){setPlaying(false);return END}return p+dt})},30);return()=>clearInterval(id)},[playing]);
 useEffect(()=>{if(playing&&scroller.current){const x=px(pos),v=scroller.current;if(x>v.scrollLeft+v.clientWidth-70)v.scrollLeft=x-v.clientWidth/3}},[pos,playing,scale]);
 const focusEvent=(i:number)=>{const v=events[i];setSelected(i);setCustom(saved[i]||'');setRange([v.t,v.end]);setPos(v.t);setPlaying(false);const newScale=i===2?210:420;jump.current=Math.max(0,v.t-800);setScale(newScale);if(newScale===scale&&scroller.current){scroller.current.scrollLeft=px(jump.current);jump.current=null}};
 const zoom=(v:number)=>{const s=Math.max(35,Math.min(700,v));const center=(scroller.current?.scrollLeft||0)/scale*1000+(scroller.current?.clientWidth||800)/scale*500;jump.current=Math.max(0,center-(scroller.current?.clientWidth||800)/s*500);setScale(s)};
 const fit=()=>{jump.current=0;setScale(Math.max(25,(scroller.current?.clientWidth||800)/22.8))};
 const selectionZoom=()=>{const [a,b]=range;jump.current=Math.max(0,a-200);setScale(Math.min(700,(scroller.current?.clientWidth||800)/Math.max(.8,(b-a+400)/1000)))};
 useEffect(()=>{const f=(ev:KeyboardEvent)=>{if((ev.target as HTMLElement).matches('input,textarea'))return;if(ev.code==='Space'){ev.preventDefault();setPlaying(p=>!p)}if(ev.key==='Escape'){setSelected(null);setRange([0,0])}};window.addEventListener('keydown',f);return()=>window.removeEventListener('keydown',f)},[]);
 useEffect(()=>{const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:unknown)=>void|Promise<void>}}).modelContext;if(!context)return;const lifecycle=new AbortController();try{void Promise.resolve(context.registerTool({name:'focus_annotation_event',title:'定位标注事件',description:'在共享时间轴中定位并放大一个打断或改口事件，同时显示其处理标注。',inputSchema:{type:'object',properties:{eventIndex:{type:'integer',minimum:0,maximum:2}},required:['eventIndex'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:unknown)=>{const i=(input as {eventIndex?:number})?.eventIndex;if(!Number.isInteger(i)||i!<0||i!>2)throw new Error('eventIndex 必须是 0、1 或 2');focusEvent(i!);await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));return {eventIndex:i,title:events[i!].title,range:[events[i!].t,events[i!].end]}}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort()},[]);
 const timeAt=(ev:React.PointerEvent<HTMLDivElement>)=>{let t=(ev.clientX-ev.currentTarget.getBoundingClientRect().left)/scale*1000;t=Math.max(0,Math.min(END,t));return snap?Math.round(t/400)*400:Math.round(t)};
 return <main className="studio">
 <header className="top"><div className="brand"><span className="brand-icon"><AudioLines size={23}/></span><b>声轨<span> / STUDIO</span></b><span className="divider"/><span className="project">天气查询 · 打断与改口</span></div><span className="prototype"><i/>交互原型</span></header>
 <div className="projectbar"><div><span className="small-label">标注项目</span><h1>对话样本 001 <span>北京天气 & 跑步提醒</span></h1></div><div className="stats"><span><b>22.8</b> 秒</span><span><b>6</b> 轨道</span><span><b>3</b> 事件</span></div></div>
 <div className="toolbar"><div className="transport"><button aria-label="回到起点" onClick={()=>{setPos(0);setPlaying(false);if(scroller.current)scroller.current.scrollLeft=0}}><SkipBack size={18}/></button><button className={'play '+(playing?'active':'')} aria-label={playing?'暂停时间轴':'播放时间轴'} onClick={()=>{if(pos>=END)setPos(0);setPlaying(v=>!v)}}>{playing?<Pause size={18}/>:<Play size={18}/>}</button><span className="timecode">{fmt(pos)} <small>/ 22.800</small></span></div><div className="tool-right"><button className={snap?'on':''} onClick={()=>setSnap(!snap)}><Brackets size={15}/>400ms 吸附</button><span className="divider"/><button onClick={()=>zoom(scale/1.4)} aria-label="缩小"><ZoomOut size={17}/></button><Slider aria-label="时间轴缩放" className="zoomslider" min={35} max={700} value={[scale]} onValueChange={v=>zoom(Array.isArray(v)?v[0]:v)}/><button onClick={()=>zoom(scale*1.4)} aria-label="放大"><ZoomIn size={17}/></button><button onClick={fit}><ScanLine size={16}/>全览</button><button onClick={selectionZoom} disabled={range[0]===range[1]}><Crosshair size={16}/>放大选区</button></div></div>
 <div className="body"><section className="editor"><div className="eventbar"><span><Flag size={15}/>关键事件</span>{events.map((v,i)=><button key={i} className={selected===i?'current':''} onClick={()=>focusEvent(i)}><i/>{v.name}<small>{fmt(v.t)}</small></button>)}</div>
 <div className="timeline-shell"><div className="track-headers"><div className="ruler-label">时间 / 秒</div>{tracks.map((t,i)=><div className={'track-name '+t.color} key={t.name}><span className="track-number">0{i+1}</span><div><b>{t.name}</b><small>{t.en}</small></div><i/></div>)}</div>
 <div className="timeline-scroll" ref={scroller}><div className="timeline" style={{width}} onPointerDown={ev=>{if(ev.button!==0)return;moved.current=false;const t=timeAt(ev);drag.current={x:ev.clientX,t};setPlaying(false);setPos(t)}} onPointerMove={ev=>{if(!drag.current)return;if(Math.abs(ev.clientX-drag.current.x)>4){moved.current=true;ev.currentTarget.setPointerCapture(ev.pointerId);const t=timeAt(ev);setRange([Math.min(t,drag.current.t),Math.max(t,drag.current.t)])}}} onPointerUp={ev=>{if(!moved.current){const t=timeAt(ev);setPos(t)}drag.current=null;if(ev.currentTarget.hasPointerCapture(ev.pointerId))ev.currentTarget.releasePointerCapture(ev.pointerId)}}>
 <div className="ruler">{Array.from({length:58},(_,i)=>i*400).map(t=><div className="tick" key={t} style={{left:px(t)}}><span>{scale>140||t%2000===0?(t/1000).toFixed(1):''}</span></div>)}</div>
 <div className="selection" style={{left:px(range[0]),width:px(range[1]-range[0])}}><span>{range[1]>range[0]?`${Math.round(range[1]-range[0])} ms`:''}</span></div>
 {events.filter(v=>v.overlap).map(v=><div className="overlap" key={v.id} style={{left:px(v.overlap![0]),width:px(v.overlap![1]-v.overlap![0])}}><span>重叠示意</span></div>)}
 {tracks.map((t,ti)=><div className={'track '+t.color} style={{backgroundSize:`${px(400)}px 100%`}} key={t.name}>{t.clips.map((c,ci)=><button key={ci} className={'clip '+(c.wave?'audio ':'')+(c.muted?'discard ':'')+(c.event===selected?'related':'')} style={{left:px(c.a),width:Math.max(5,px(c.b-c.a)-3)}} title={c.label} onClick={()=>{if(moved.current)return;if(c.event!==undefined){setSelected(c.event);setCustom(saved[c.event]||'');setRange([events[c.event].t,events[c.event].end])}else{setSelected(null);setRange([c.a,c.b])}}}><span>{c.label}</span>{c.wave?<Wave width={Math.max(5,px(c.b-c.a)-16)} seed={ci+ti*8}/>:<small>{c.sub|| (c.muted?'未播出 / 丢弃':`${fmt(c.a)} — ${fmt(c.b)}`)}</small>}</button>)}</div>)}
 {events.map(v=><div className="eventline" key={v.id} style={{left:px(v.t)}}><button onClick={()=>focusEvent(v.id)}>{v.id+1}</button></div>)}<div className="playhead" style={{left:px(pos)}}><span/></div>
 </div></div></div>
 <div className="bottom"><span><MousePointer2 size={14}/>拖动选区 · 点击片段查看标注 · 空格播放 / 暂停</span><span>{range[1]>range[0]?`${fmt(range[0])} — ${fmt(range[1])}`:'未选择区间'}</span></div>
 <div className="notice"><Clock3 size={15}/><span>演示波形，无真实音频。橙色重叠尾部为示意，精确停声时间待实测；播放仅移动时间轴。</span></div>
 </section>
 <aside className="inspector"><div className="inspector-top"><span><SlidersHorizontal size={16}/>标注检查器</span><span className="small-label">{e?'EVENT 0'+(e.id+1):'SELECTION'}</span></div>{e?<><div className="event-title"><span className="badge">{e.tag}</span><h2>{e.title}</h2><p>{fmt(e.t)} <ChevronRight size={13}/> {fmt(e.end)}</p></div><blockquote>{e.quote}</blockquote><div className="section-title">特殊处理 <span>{e.actions.length} 项</span></div><ol className="actions">{e.actions.map((a,i)=><li key={a}><span>{i+1}</span>{a}</li>)}</ol><div className="tool-state"><i/>{e.tool}</div><div className="section-title">回复与实播</div><dl className="reply-details"><dt>完整计划</dt><dd>{e.plan}</dd><dt>实际播出</dt><dd>{e.heard}</dd><dt className="red">丢弃 / 抑制</dt><dd className="discarded"><X size={14}/>{e.drop}</dd></dl><p className="explanation">{e.note}</p><details><summary>精确时间戳 <span>待采集</span></summary><div className="timestamps">{['用户起声','打断检出','停播指令','实际停声'].map((v,i)=><div key={v}><span>t{i+1} · {v}</span><span>— ms</span></div>)}<p>微轮次区间不是实测延迟，演示重叠不用于计算。</p></div></details><label className="note-label" htmlFor="note">标注备注</label><textarea id="note" value={custom} onChange={ev=>{setCustom(ev.target.value);setSaved({...saved,[e.id]:ev.target.value})}} placeholder="记录这个事件的观察…"/><small className="session-note">备注仅保留在本次页面会话</small></>:<div className="empty-inspector"><MousePointer2/><h2>已选区间</h2><p>{fmt(range[0])} — {fmt(range[1])}</p><button onClick={selectionZoom}>放大查看选区</button><p>点击橙色事件标记，查看打断与工具处理。</p></div>}</aside></div>
 </main>;
}
