'use client';
import { useEffect, useRef, useState } from 'react';
import { Slider } from '@/components/ui/slider';
import { Play, Pause, SkipBack, ZoomIn, ZoomOut, ScanLine, MousePointer2, ChevronRight, AudioLines, SlidersHorizontal, Flag, X, Crosshair, Brackets, Clock3 } from 'lucide-react';
const END=22800;
const fmt=(n:number)=>(n/1000).toFixed(3)+' s';
type Clip={a:number;b:number;label:string;sub?:string;event?:number;wave?:boolean;muted?:boolean};
const events=[
 {id:0,t:3600,end:4000,name:'Interrupt 01',title:'Clarification during wait',quote:'“主要……看下午，我要出去跑步。”',tag:'Interruption',plan:'嗯……好的，你稍等一下，我来看看。',heard:'嗯……好的，你稍等一下……',drop:'我来看看',actions:['Detect user speech and yield the floor','Stop playback with audio.stop()','Keep weather.query running','Add afternoon and running context'],tool:'Query running · No new request',note:'The pending query includes hourly data. Stopping playback does not cancel the request.',overlap:[3600,3760]},
 {id:1,t:12000,end:12400,name:'Interrupt 02',title:'Time range changed',quote:'“那上午呢？”',tag:'Interruption',plan:'明天下午三点左右有小雨，气温二十度，跑步可以……',heard:'明天下午三点左右有小雨……',drop:'气温二十度，跑步可以……',actions:['Switch to morning; stop the afternoon response','Stop playback with audio.stop()','Read morning weather from the existing result','Prepare a new response about running'],tool:'Cached result · No API call',note:'The revised morning response plays from 12.800 to 15.600 s.',overlap:[12000,12160]},
 {id:2,t:18400,end:19600,name:'Revision 03',title:'Reminder time revised',quote:'“不，改成九点。”',tag:'Intent revision',plan:'Create a running reminder for tomorrow at 08:00; check the result against the latest intent.',heard:'行。',drop:'Outdated confirmation of the 08:00 reminder',actions:['Set the latest target to 09:00','Wait for R1 to return the 08:00 reminder','reminder.update(id, 09:00)','Confirm only after the update succeeds'],tool:'R1 → update → success',note:'User speech overlaps the tool request. The assistant is silent; this is not overlapping audio.',overlap:null},
];
const tracks:{name:string;en:string;color:string;clips:Clip[]}[]=[
 {name:'User',en:'Audio',color:'green',clips:[{a:0,b:2400,label:'帮我看看明天北京的天气。',wave:true},{a:3600,b:5600,label:'主要看下午，我要出去跑步。',wave:true,event:0},{a:12000,b:12400,label:'那上午呢？',wave:true,event:1},{a:15600,b:18000,label:'明天早上八点提醒我跑步。',wave:true},{a:18400,b:19600,label:'不，改成九点。',wave:true,event:2}]},
 {name:'Assistant',en:'Audio output',color:'blue',clips:[{a:2400,b:3760,label:'嗯……好的，你稍等一下……',wave:true,event:0,sub:'0.85× speed · Illustrative tail'},{a:5600,b:6800,label:'行，我看看下午适不适合跑步。',wave:true},{a:10800,b:12160,label:'明天下午三点左右有小雨……',wave:true,event:1},{a:12800,b:15600,label:'上午多云，十七到十九度，比下午更适合跑步。',wave:true},{a:18000,b:18400,label:'行。',wave:true},{a:20400,b:22800,label:'设好了，明天早上九点提醒你跑步。',wave:true}]},
 {name:'Reasoning',en:'Intent & context',color:'amber',clips:[{a:0,b:2400,label:'Extract Beijing / tomorrow'},{a:3600,b:5600,label:'Detect speech → yield',event:0},{a:5600,b:10400,label:'Afternoon + running · Listening'},{a:10400,b:10800,label:'Read afternoon weather'},{a:12000,b:12800,label:'Switch to morning · Keep running context',event:1},{a:15600,b:18000,label:'New task: running tomorrow at 08:00'},{a:18400,b:20400,label:'Latest target → 09:00',event:2}]},
 {name:'Audio control',en:'Playback events',color:'pink',clips:[{a:3600,b:4000,label:'audio.stop()',sub:'Detection / command / stop: unmeasured',event:0},{a:12000,b:12400,label:'audio.stop()',sub:'Discard remaining afternoon response',event:1}]},
 {name:'Tools',en:'Async requests',color:'teal',clips:[{a:2400,b:10400,label:'weather.query(Beijing, tomorrow)',sub:'8,000 ms · Continues after playback stops',event:0},{a:12000,b:12800,label:'Read cached morning data',event:1},{a:18000,b:19600,label:'R1 · create(08:00)',sub:'Intent revised while pending',event:2},{a:19600,b:20400,label:'update(09:00)',sub:'Confirm on success',event:2}]},
 {name:'Response plan',en:'Planned & discarded',color:'purple',clips:[{a:2400,b:3600,label:'嗯……好的，你稍等一下，我来看看。',event:0},{a:3600,b:4000,label:'Discard: 我来看看',muted:true,event:0},{a:6800,b:10400,label:'Silent wait · No filler'},{a:10400,b:12000,label:'Afternoon rain, 20°C, running advice',event:1},{a:12000,b:12400,label:'Discard: afternoon advice',muted:true,event:1},{a:12400,b:15600,label:'Prepare morning running advice'},{a:18400,b:20400,label:'Suppress stale 08:00 result',muted:true,event:2},{a:20400,b:22800,label:'Confirm tomorrow at 09:00'}]},
];
function Wave({width,seed}:{width:number;seed:number}){const n=Math.max(3,Math.floor(width/5));return <svg className="wave" width={width} height="32" aria-hidden="true">{Array.from({length:n},(_,i)=>{const h=3+Math.abs(Math.sin(i*1.8+seed)*Math.cos(i*.23+seed))*26;return <line key={i} x1={i*5+2} x2={i*5+2} y1={(32-h)/2} y2={(32+h)/2}/>})}</svg>}
export default function Studio(){
 const [scale,setScale]=useState(210),[pos,setPos]=useState(3600),[playing,setPlaying]=useState(false),[selected,setSelected]=useState<number|null>(0),[range,setRange]=useState<[number,number]>([3600,4000]),[snap,setSnap]=useState(false),[custom,setCustom]=useState(''),[saved,setSaved]=useState<Record<number,string>>({});
 const scroller=useRef<HTMLDivElement>(null),drag=useRef<{x:number;t:number}|null>(null),moved=useRef(false),jump=useRef<number|null>(2400);
 const width=END/1000*scale,e=selected===null?null:events[selected];
 const px=(t:number)=>t/1000*scale;
 useEffect(()=>{if(jump.current!==null&&scroller.current){scroller.current.scrollLeft=jump.current/1000*scale;jump.current=null}},[scale]);
 useEffect(()=>{if(!playing)return;let prev=performance.now();const id=setInterval(()=>{const now=performance.now(),dt=now-prev;prev=now;setPos(p=>{if(p+dt>=END){setPlaying(false);return END}return p+dt})},30);return()=>clearInterval(id)},[playing]);
 useEffect(()=>{if(playing&&scroller.current){const x=px(pos),v=scroller.current;if(x>v.scrollLeft+v.clientWidth-70)v.scrollLeft=x-v.clientWidth/3}},[pos,playing,scale]);
 const focusEvent=(i:number)=>{const v=events[i];setSelected(i);setCustom(saved[i]||'');setRange([v.t,v.end]);setPos(v.t);setPlaying(false);const newScale=i===2?210:420;jump.current=Math.max(0,v.t-800);setScale(newScale);if(newScale===scale&&scroller.current){scroller.current.scrollLeft=px(jump.current);jump.current=null}};
 const zoom=(v:number)=>{const s=Math.max(35,Math.min(700,v));const center=(scroller.current?.scrollLeft||0)/scale*1000+(scroller.current?.clientWidth||800)/scale*500;jump.current=Math.max(0,center-(scroller.current?.clientWidth||800)/s*500);setScale(s)};
 const fit=()=>{jump.current=0;setScale(Math.max(25,(scroller.current?.clientWidth||800)/22.8))};
 const selectionZoom=()=>{const [a,b]=range;jump.current=Math.max(0,a-200);setScale(Math.min(700,(scroller.current?.clientWidth||800)/Math.max(.8,(b-a+400)/1000)))};
 useEffect(()=>{const f=(ev:KeyboardEvent)=>{if((ev.target as HTMLElement).matches('input,textarea'))return;if(ev.code==='Space'){ev.preventDefault();setPlaying(p=>!p)}if(ev.key==='Escape'){setSelected(null);setRange([0,0])}};window.addEventListener('keydown',f);return()=>window.removeEventListener('keydown',f)},[]);
 useEffect(()=>{const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:unknown)=>void|Promise<void>}}).modelContext;if(!context)return;const lifecycle=new AbortController();try{void Promise.resolve(context.registerTool({name:'focus_annotation_event',title:'Focus annotation event',description:'Focus and zoom an interruption or revision event and show its annotations.',inputSchema:{type:'object',properties:{eventIndex:{type:'integer',minimum:0,maximum:2}},required:['eventIndex'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:unknown)=>{const i=(input as {eventIndex?:number})?.eventIndex;if(!Number.isInteger(i)||i!<0||i!>2)throw new Error('eventIndex must be 0, 1, or 2');focusEvent(i!);await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));return {eventIndex:i,title:events[i!].title,range:[events[i!].t,events[i!].end]}}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort()},[]);
 const timeAt=(ev:React.PointerEvent<HTMLDivElement>)=>{let t=(ev.clientX-ev.currentTarget.getBoundingClientRect().left)/scale*1000;t=Math.max(0,Math.min(END,t));return snap?Math.round(t/400)*400:Math.round(t)};
 return <main className="studio">
 <header className="top"><div className="brand"><AudioLines size={21}/><b>Track Studio</b><span className="divider"/><span className="project">Weather query / interruptions</span></div><span className="prototype">Prototype</span></header>
 <div className="projectbar"><div><span className="small-label">ANNOTATION SESSION</span><h1>Conversation 001 <span>Beijing weather / running reminder</span></h1></div><div className="stats"><span><b>22.8</b> sec</span><span><b>6</b> tracks</span><span><b>3</b> events</span></div></div>
 <div className="toolbar"><div className="transport"><button aria-label="Go to start" onClick={()=>{setPos(0);setPlaying(false);if(scroller.current)scroller.current.scrollLeft=0}}><SkipBack size={18}/></button><button className={'play '+(playing?'active':'')} aria-label={playing?'Pause timeline':'Play timeline'} onClick={()=>{if(pos>=END)setPos(0);setPlaying(v=>!v)}}>{playing?<Pause size={18}/>:<Play size={18}/>}</button><span className="timecode">{fmt(pos)} <small>/ 22.800</small></span></div><div className="tool-right"><button className={snap?'on':''} onClick={()=>setSnap(!snap)}><Brackets size={15}/>Snap 400 ms</button><span className="divider"/><button onClick={()=>zoom(scale/1.4)} aria-label="Zoom out"><ZoomOut size={17}/></button><Slider aria-label="Timeline zoom" className="zoomslider" min={35} max={700} value={[scale]} onValueChange={v=>zoom(Array.isArray(v)?v[0]:v)}/><button onClick={()=>zoom(scale*1.4)} aria-label="Zoom in"><ZoomIn size={17}/></button><button onClick={fit}><ScanLine size={16}/>Fit</button><button onClick={selectionZoom} disabled={range[0]===range[1]}><Crosshair size={16}/>Zoom selection</button></div></div>
 <div className="body"><section className="editor"><div className="eventbar"><span><Flag size={15}/>Events</span>{events.map((v,i)=><button key={i} className={selected===i?'current':''} onClick={()=>focusEvent(i)}>{v.name}<small>{fmt(v.t)}</small></button>)}</div>
 <div className="timeline-shell"><div className="track-headers"><div className="ruler-label">Time / seconds</div>{tracks.map((t,i)=><div className={'track-name '+t.color} key={t.name}><span className="track-number">0{i+1}</span><div><b>{t.name}</b><small>{t.en}</small></div></div>)}</div>
 <div className="timeline-scroll" ref={scroller}><div className="timeline" style={{width}} onPointerDown={ev=>{if(ev.button!==0)return;moved.current=false;const t=timeAt(ev);drag.current={x:ev.clientX,t};setPlaying(false);setPos(t)}} onPointerMove={ev=>{if(!drag.current)return;if(Math.abs(ev.clientX-drag.current.x)>4){moved.current=true;ev.currentTarget.setPointerCapture(ev.pointerId);const t=timeAt(ev);setRange([Math.min(t,drag.current.t),Math.max(t,drag.current.t)])}}} onPointerUp={ev=>{if(!moved.current){const t=timeAt(ev);setPos(t)}drag.current=null;if(ev.currentTarget.hasPointerCapture(ev.pointerId))ev.currentTarget.releasePointerCapture(ev.pointerId)}}>
 <div className="ruler">{Array.from({length:58},(_,i)=>i*400).map(t=><div className="tick" key={t} style={{left:px(t)}}><span>{scale>140||t%2000===0?(t/1000).toFixed(1):''}</span></div>)}</div>
 <div className="selection" style={{left:px(range[0]),width:px(range[1]-range[0])}}><span>{range[1]>range[0]?`${Math.round(range[1]-range[0])} ms`:''}</span></div>
 {events.filter(v=>v.overlap).map(v=><div className="overlap" key={v.id} style={{left:px(v.overlap![0]),width:px(v.overlap![1]-v.overlap![0])}}><span>Overlap*</span></div>)}
 {tracks.map((t,ti)=><div className={'track '+t.color} style={{backgroundSize:`${px(400)}px 100%`}} key={t.name}>{t.clips.map((c,ci)=><button key={ci} className={'clip '+(c.wave?'audio ':'')+(c.muted?'discard ':'')+(c.event===selected?'related':'')} style={{left:px(c.a),width:Math.max(5,px(c.b-c.a)-3)}} title={c.label} onClick={()=>{if(moved.current)return;if(c.event!==undefined){setSelected(c.event);setCustom(saved[c.event]||'');setRange([events[c.event].t,events[c.event].end])}else{setSelected(null);setRange([c.a,c.b])}}}><span>{c.label}</span>{c.wave?<Wave width={Math.max(5,px(c.b-c.a)-16)} seed={ci+ti*8}/>:<small>{c.sub|| (c.muted?'Not played / discarded':`${fmt(c.a)} — ${fmt(c.b)}`)}</small>}</button>)}</div>)}
 {events.map(v=><div className="eventline" key={v.id} style={{left:px(v.t)}}><button onClick={()=>focusEvent(v.id)}>{v.id+1}</button></div>)}<div className="playhead" style={{left:px(pos)}}><span/></div>
 </div></div></div>
 <div className="bottom"><span><MousePointer2 size={14}/>Drag to select · Click to inspect · Space to play / pause</span><span>{range[1]>range[0]?`${fmt(range[0])} — ${fmt(range[1])}`:'No selection'}</span></div>
 <div className="notice"><Clock3 size={15}/><span>Illustrative waveforms and overlap. Stop timing is unmeasured. Playback moves the playhead only.</span></div>
 </section>
 <aside className="inspector"><div className="inspector-top"><span><SlidersHorizontal size={16}/>Inspector</span><span className="small-label">{e?'EVENT 0'+(e.id+1):'SELECTION'}</span></div>{e?<><div className="event-title"><span className="badge">{e.tag}</span><h2>{e.title}</h2><p>{fmt(e.t)} <ChevronRight size={13}/> {fmt(e.end)}</p></div><blockquote>{e.quote}</blockquote><div className="section-title">Handling <span>{e.actions.length} actions</span></div><ol className="actions">{e.actions.map((a,i)=><li key={a}><span>{i+1}</span>{a}</li>)}</ol><div className="tool-state">{e.tool}</div><div className="section-title">Response</div><dl className="reply-details"><dt>Planned</dt><dd>{e.plan}</dd><dt>Played</dt><dd>{e.heard}</dd><dt className="red">Discarded / suppressed</dt><dd className="discarded"><X size={14}/>{e.drop}</dd></dl><p className="explanation">{e.note}</p><details><summary>Precise timestamps <span>Unmeasured</span></summary><div className="timestamps">{['Speech onset','Interruption detected','Stop command','Playback stopped'].map((v,i)=><div key={v}><span>t{i+1} · {v}</span><span>— ms</span></div>)}<p>Micro-turn intervals are not measured latency. Do not calculate timing from the illustrative overlap.</p></div></details><label className="note-label" htmlFor="note">Notes</label><textarea id="note" value={custom} onChange={ev=>{setCustom(ev.target.value);setSaved({...saved,[e.id]:ev.target.value})}} placeholder="Add an observation…"/><small className="session-note">Notes are kept for this page session only.</small></>:<div className="empty-inspector"><MousePointer2/><h2>Selected range</h2><p>{fmt(range[0])} — {fmt(range[1])}</p><button onClick={selectionZoom}>Zoom to selection</button><p>Select an event marker to inspect interruption and tool handling.</p></div>}</aside></div>
 </main>;
}
