import {useEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import type {Scenario} from '../app/page';
import {buildCaseData} from './case-data';
import {synthesize,tarFiles,type Synthesis,type SpeechClip} from './audio/synthesis';
import {AudioLines,Download,X,Play,Pause,SkipBack} from './sf-symbols';
export function SynthesisPanel({caseId,caseTitle,scenario,enabled,timelinePlaying,onOpen}:{caseId:string;caseTitle:string;scenario:Scenario;enabled:boolean;timelinePlaying:boolean;onOpen:()=>void}){
 const dialog=useRef<HTMLElement>(null),trigger=useRef<HTMLButtonElement>(null),audio=useRef<HTMLAudioElement>(null);
 const [busy,setBusy]=useState(false),[packing,setPacking]=useState(false),[error,setError]=useState(''),[result,setResult]=useState<Synthesis|null>(null),[url,setUrl]=useState(''),[time,setTime]=useState(0),[zoom,setZoom]=useState(1),[playing,setPlaying]=useState(false),[opened,setOpened]=useState(false);
 const stateKey=`track-studio-audio-preview-open:${caseId}`;
 const remember=(value:boolean)=>{try{localStorage.setItem(stateKey,String(value))}catch{}};
 const mounted=useRef(true);useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;audio.current?.pause()}},[]);
 useEffect(()=>{if(!result)return;const u=URL.createObjectURL(result.wav);setUrl(u);return()=>URL.revokeObjectURL(u)},[result]);
 const open=async(restore=false)=>{if(busy)return;setBusy(true);setError('');if(!restore)onOpen();try{const clips:SpeechClip[]=scenario.tracks.filter(t=>t.name==='用户'||t.name==='助手').flatMap(t=>t.clips.filter(c=>!c.muted&&!c.discardTail&&c.b>c.a&&(c.wave||c.audioKey)).map(c=>({...c,role:t.name==='用户'?'user' as const:'assistant' as const})));const value=await synthesize(caseId,scenario.END,clips);if(!mounted.current)return;setResult(value);setTime(0);setOpened(true);remember(true)}catch(e){if(mounted.current)setError(e instanceof Error?e.message:'合成失败，请重试。')}finally{if(mounted.current)setBusy(false)}};
 useEffect(()=>{try{if(enabled&&localStorage.getItem(stateKey)==='true')void open(true)}catch{}},[]);
 useEffect(()=>{if(timelinePlaying)audio.current?.pause()},[timelinePlaying]);
 const close=()=>{audio.current?.pause();setOpened(false);remember(false);trigger.current?.focus()};
 const download=async()=>{if(!result||packing)return;setPacking(true);setError('');try{const {document:json}=buildCaseData({caseId,caseTitle,durationMs:scenario.END,events:scenario.inputEvents,utterances:scenario.utterances,controls:scenario.controlAnnotations,metaOverride:scenario.meta});const exportJson={...json,meta_data:{...json.meta_data,media:{...json.meta_data.media,audio:{...json.meta_data.media.audio,file:'audio.wav',sample_rate:result.sampleRate,channels:2,encoding:'PCM_16'}}}};const archive=await tarFiles([{name:'audio.wav',blob:result.wav},{name:'case.json',blob:new Blob([JSON.stringify(exportJson,null,2)+'\n'],{type:'application/json'})}]);const u=URL.createObjectURL(archive),link=document.createElement('a');link.href=u;link.download=caseTitle.replace(/[\\/:*?"<>|]/g,'-')+'.tar';dialog.current?.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(u),1000)}catch{setError('下载文件打包失败，请重试。')}finally{setPacking(false)}};
 return <><button ref={trigger} disabled={!enabled||busy} aria-expanded={opened} aria-controls="case-audio-preview" className={opened?'on':undefined} aria-busy={busy} aria-label={busy?'正在生成完整合成数据':'查看完整合成数据'} title={busy?'正在生成完整合成数据':'查看完整合成数据'} onClick={()=>opened?close():void open()}>{busy?<span className="synthesis-spinner"/>:<AudioLines size={18}/>}</button>{error&&!opened&&<div className="synthesis-error" role="alert">{error}<button aria-label="关闭提示" onClick={()=>setError('')}><X size={14}/></button></div>}
 {opened&&document.getElementById('case-preview-dock')&&createPortal(<section ref={dialog} id="case-audio-preview" className="synthesis-panel" aria-label="音频预览" onKeyDown={e=>{if(e.key==='Escape'){e.stopPropagation();close()}if(e.code==='Space'||e.code==='Enter')e.stopPropagation()}}>

 <header><span className="synthesis-editor-label">音频预览</span><div><h2 id="synthesis-title">{caseTitle}</h2><p>完整合成数据 · {((result?.durationMs??0)/1000).toFixed(3)} 秒 · 48 kHz · 双声道 WAV</p></div><button className="synthesis-download" disabled={packing} aria-busy={packing} aria-label={packing?'正在打包 TAR':'下载 TAR'} title={packing?'正在打包 TAR':'下载 TAR'} onClick={()=>void download()}>{packing?<span className="synthesis-spinner"/>:<Download size={18}/>}</button><button className="synthesis-close" aria-label="关闭合成数据面板" title="关闭 · Esc" onClick={close}><X size={18}/></button></header>
 {result&&<><div className="synthesis-editor-body"><aside className="synthesis-amplitude" aria-label="振幅百分比"><div className="synthesis-axis-title">%</div>{['L','R'].map(ch=><div className="synthesis-axis-channel" key={ch}><span>{ch}</span><div>{[100,50,0,-50,-100].map(v=><small key={v}>{v}</small>)}</div></div>)}</aside><div className="synthesis-wave-scroll"><div className="synthesis-wave-content" style={{width:`${zoom*100}%`}} onClick={e=>{const r=e.currentTarget.getBoundingClientRect(),seconds=Math.max(0,Math.min(result.durationMs/1000,(e.clientX-r.left)/r.width*result.durationMs/1000));if(audio.current){audio.current.currentTime=seconds;setTime(seconds)}}}>
 <div className="synthesis-ruler">{Array.from({length:Math.ceil(result.durationMs/1000)+1},(_,i)=><span key={i} style={{left:`${i*1000/result.durationMs*100}%`}}>{i%Math.max(1,Math.ceil(result.durationMs/1000/(12*zoom)))===0?i:''}</span>)}</div>
 {result.peaks.map((peaks,ch)=><div className={'synthesis-channel channel-'+ch} key={ch}><div className="synthesis-channel-label">audio.wav <span>{ch===0?'L · 用户':'R · 助手'}</span></div><div className="synthesis-wave-plot"><svg viewBox="0 0 2000 100" preserveAspectRatio="none" aria-label={ch===0?'用户左声道完整波形':'助手右声道完整波形'} role="img"><line x1="0" y1="50" x2="2000" y2="50" className="synthesis-zero"/><path d={'M0 50 '+peaks.map((p,i)=>`L${i} ${50-p*49}`).join(' ')+' '+peaks.map((_,i)=>{const j=peaks.length-1-i;return `L${j} ${50+peaks[j]*49}`}).join(' ')+' Z'}/></svg></div></div>)}<div className="synthesis-cursor" style={{left:`${time*1000/result.durationMs*100}%`}}><span/></div></div></div></div>
 <footer><audio ref={audio} src={url||undefined} onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onEnded={()=>setPlaying(false)} onTimeUpdate={()=>setTime(audio.current?.currentTime??0)}/><div className="synthesis-transport"><button title="回到音频起点" aria-label="回到音频起点" onClick={()=>{if(audio.current){audio.current.currentTime=0;setTime(0)}}}><SkipBack size={18}/></button><button title={playing?'暂停合成音频':'播放合成音频'} aria-label={playing?'暂停合成音频':'播放合成音频'} onClick={()=>{if(playing)audio.current?.pause();else {onOpen();void audio.current?.play().catch(()=>setError('音频暂时无法播放，请重试。'))}}}>{playing?<Pause size={18}/>:<Play size={18}/>}</button></div><span className="synthesis-position">{time.toFixed(3)} <small>/ {(result.durationMs/1000).toFixed(3)} 秒</small></span><label>缩放<input aria-label="合成波形缩放" type="range" min="1" max="8" step=".25" value={zoom} onChange={e=>setZoom(Number(e.target.value))}/></label><span>点击波形定位</span></footer></>}{error&&<p role="alert" className="synthesis-panel-error">{error}</p>}
 </section>,document.getElementById('case-preview-dock')! )}</>;
}
